/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-10 00:56:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.FileVO;
import board.model.vo.Board;
import java.util.ArrayList;
import member.model.vo.Member;

public final class 마이_005f페이지_0028메인_0029_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/Member/../Common/footer.jsp", Long.valueOf(1598887312249L));
    _jspx_dependants.put("/WEB-INF/views/Member/../Common/header.jsp", Long.valueOf(1599364317178L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.FileVO");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member member = (Member)request.getAttribute("member");
	FileVO profile = (FileVO)request.getAttribute("profile");
	ArrayList<Board> supportList = (ArrayList<Board>)request.getAttribute("supportList");
	ArrayList<Board> externalList = (ArrayList<Board>)request.getAttribute("externalList");
	ArrayList<Board> commuFreeList = (ArrayList<Board>)request.getAttribute("commuFreeList");
	ArrayList<Board> qaList = (ArrayList<Board>)request.getAttribute("qaList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이 페이지(메인)</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/body.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".box {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tborder-radius: 70%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_area {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_box {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tpadding-top: 24px;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_box a {\r\n");
      out.write("\t/* text-decoration: none; */\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t/* color: white; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_box a:hover {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("/* .my_util_area li:hover {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\t} */\r\n");
      out.write(".box_title {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tbackground-color: rgb(15, 76, 130);\r\n");
      out.write("\tborder-radius: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box_title h3 {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*파일 업로드 관련 */\r\n");
      out.write(".where {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 25px 15px;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-family: verdana;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: -1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclip: rect(0, 0, 0, 0);\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #fdfdfd;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* named upload */\r\n");
      out.write(".filebox .upload-name {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("\t-webkit-appearance: none; /* 네이티브 외형 감추기 */\r\n");
      out.write("\t-moz-appearance: none;\r\n");
      out.write("\tappearance: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* imaged preview */\r\n");
      out.write(".filebox .upload-display { /* 이미지가 표시될 지역 */\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.filebox .upload-display {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin-right: 5px;\r\n");
      out.write("\t\tmargin-bottom: 0;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox .upload-thumb-wrap { /* 추가될 이미지를 감싸는 요소 */\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 54px;\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox .upload-display img { /* 추가될 이미지 */\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\twidth: 100% \\9;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.min.js\"></script> \r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("header {\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".header_top {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write(".top {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  float: right;\r\n");
      out.write("  padding-right: 10%;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding-top: 4px;\r\n");
      out.write("}\r\n");
      out.write(".top_btn {\r\n");
      out.write("  margin: 1px;\r\n");
      out.write("  padding: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".top_btn:hover {\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".lagefont {\r\n");
      out.write("  font-size: 60px;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_dropdown:hover .navbar_dropdown-content {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  background-color: #f9f9f9;\r\n");
      out.write("  min-width: 100px;\r\n");
      out.write("  max-width: 100px;\r\n");
      out.write("  box-shadow: 0px 0px 0px 2px rgba(0,0,0,0.2);\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 5px 6px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-table;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a:hover{\r\n");
      out.write("\t background-color: #f5f5f5;\r\n");
      out.write("  \tfont-weight: bold;\r\n");
      out.write("  \tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_menu {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding: 40px 0px;\r\n");
      out.write("  padding-right: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li {\r\n");
      out.write("  border-right: 1px solid silver;\r\n");
      out.write("  padding: 8px 12px; /* 마우스 선택영역이 넓어짐 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li:hover {\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("header {\r\n");
      out.write("  height: auto;\r\n");
      out.write("}\r\n");
      out.write("  .navbar {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .navbar_title {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 0px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu li {\r\n");
      out.write("    border-right: 0px solid silver;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    padding: 8px 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .top {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_logo img {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header_top\">\r\n");
      out.write("         <div class=\"top\">\r\n");
      out.write("         ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/insertForm.me\" class=\"top_btn\"><b>회원가입</b></a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/loginPage.me\" class=\"top_btn\"><b>로그인</b></a></li>\r\n");
      out.write("         ");
 } else { 
      out.write("\r\n");
      out.write("         \t<li><label>");
      out.print( loginUser.getMemberName() );
      out.write("님의 방문을 환영합니다.</label></li>\r\n");
      out.write("         \t");
 if(loginUser.getMemberName().equals("관리자")) { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage.ad\" class=\"top_btn\"><b>관리자 페이지</b></a></li>\r\n");
      out.write("         \t");
 } else { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage.me\" class=\"top_btn\"><b>마이페이지</b></a></li>\r\n");
      out.write("        \t ");
 } 
      out.write("\r\n");
      out.write("         \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" class=\"top_btn\"><b>로그아웃</b></a></li>\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     <nav class=\"navbar\">\r\n");
      out.write("         <div class=\"navbar_title\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Main.mi\"><span class=\"lagefont\">정</span>부지원금<span class=\"lagefont\">바</span>로 지금</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_menu\">\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.no\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.sp\">지원정책</a></li>\r\n");
      out.write("             <li class=\"navbar_dropdown\">\r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\" class=\"navbar_dropbtn\">커뮤니티</a>\r\n");
      out.write("             <div class='navbar_dropdown-content'>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\">자유게시판</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/spMain.cm\">지원정책</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/eaMain.cm\">대외활동</a>\r\n");
      out.write("             </div>\r\n");
      out.write("           </li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.ea\">대외활동</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.fa\">묻고 답하기</a></li>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_logo\">\r\n");
      out.write("            <img id=\"logo\" src=\"Media/logo.png\" width = \"80px\" height = \"80px\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("   </header> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<aside>\r\n");
      out.write("\t\t\t<h2>마이페이지</h2>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<h2>나의게시물</h2>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPageSupport.me\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>지원정책 게시판</h3>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPageExternal.me\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>대외활동 게시판</h3>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPageCommuFree.me\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>자유게시판</h3>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPageQA.me\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Q / A</h3>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberInfo.me\">\r\n");
      out.write("\t\t\t\t<h2>회원정보</h2>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/changePwdCf.me\">\r\n");
      out.write("\t\t\t\t<h2>비밀번호 변경</h2>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteForm.me\">\r\n");
      out.write("\t\t\t\t<h2>회원탈퇴</h2>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main_section\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"box\" style=\"background: #BDBDBD;\">\r\n");
      out.write("\t\t\t\t");
if(profile == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"profile\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UploadFolder/member_profile/profileDefault.png\">\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"profile\" src=\"");
      out.print( request.getContextPath() );
      out.write("/UploadFolder/member_profile/");
      out.print(profile.getChangeName());
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"filebox bs3-primary preview-image\">\r\n");
      out.write("\t           \t");
if(profile == null) { 
      out.write("\r\n");
      out.write("\t           \t<form action = \"");
      out.print( request.getContextPath() );
      out.write("/insertProfile.me\" method=\"post\" encType=\"multipart/form-data\">\r\n");
      out.write("\t\t           \t<input class=\"upload-name\" value=\"파일선택\" disabled=\"disabled\" style=\"width: 200px;\">\r\n");
      out.write("\t\t            <label for=\"input_file\">프로필 업로드</label> \r\n");
      out.write("\t\t            <input type=\"file\" id=\"input_file\" class=\"upload-hidden\" name=\"profileFile\"><br>\r\n");
      out.write("\t\t           \t<input type=\"submit\" value=\"업로드\">\r\n");
      out.write("\t\t    \t</form>\r\n");
      out.write("\t            ");
 } else { 
      out.write("\r\n");
      out.write("\t           \t<form action = \"");
      out.print( request.getContextPath() );
      out.write("/updateProfile.me\" method=\"post\" encType=\"multipart/form-data\">\r\n");
      out.write("\t            \t<input type=\"hidden\" value=\"");
      out.print(profile.getFileNo());
      out.write("\" name=\"originalFileNo\">\r\n");
      out.write("\t            \t<input class=\"upload-name\" value=\"파일선택\" disabled=\"disabled\" style=\"width: 200px;\">\r\n");
      out.write("\t\t            <label for=\"input_file\">프로필 수정</label> \r\n");
      out.write("\t\t            <input type=\"file\" id=\"input_file\" class=\"upload-hidden\" name=\"profileFile\"><br>\r\n");
      out.write("\t\t            <input type=\"submit\" value=\"업로드\">\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t\t        <form action = \"");
      out.print( request.getContextPath() );
      out.write("/deleteProfile.me\" method=\"post\" encType=\"multipart/form-data\">\r\n");
      out.write("\t\t        \t<input type=\"hidden\" value=\"");
      out.print(profile.getFileNo());
      out.write("\" name=\"originalFileNo\">\r\n");
      out.write("\t\t        \t<input type=\"submit\" value=\"프로필 삭제\"><br>\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t\t        ");
 } 
      out.write(" \r\n");
      out.write("\t\t\r\n");
      out.write("\t     \t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"my_board\">\r\n");
      out.write("\t\t\t\t<h1 align='left'>내가 쓴 글</h1>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div class=\"board_area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"board_box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><h3>지원정책</h3></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ol id=\"sp_title\">\r\n");
      out.write("\t\t\t\t\t\t");
 if(supportList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"area_title\">조회된 리스트가 없습니다.</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else if(supportList.size() >= 3) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < 4; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 Board b = supportList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"enroll\" type=\"hidden\" value=\"");
      out.print(b.getEnrollState() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (Board b : supportList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"enroll\" type=\"hidden\" value=\"");
      out.print(b.getEnrollState() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t        \t\t$(function(){\r\n");
      out.write("\t\t\t\t\t            $('#sp_title .area_list').mouseenter(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css({'cursor':'pointer'});\r\n");
      out.write("\t\t\t\t\t            }).mouseout(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css('none');\r\n");
      out.write("\t\t\t\t\t            }).click(function(){\r\n");
      out.write("\t\t\t\t\t            \tvar bId = $(this).parent().children('input').val();\r\n");
      out.write("\t\t\t\t\t            \tvar enroll = $(this).parent().children('#enroll').val();\r\n");
      out.write("\t\t\t\t            \t\tif(enroll == 'N'){\r\n");
      out.write("\t\t\t\t\t            \t\tlocation.href = '");
      out.print( request.getContextPath() );
      out.write("/spDetail.cm?bId=' + bId;\r\n");
      out.write("\t\t\t\t            \t\t} else {\r\n");
      out.write("\t\t\t\t            \t\t\tlocation.href = '");
      out.print( request.getContextPath() );
      out.write("/detail.sp?bId=' + bId;\r\n");
      out.write("\t\t\t\t            \t\t}\r\n");
      out.write("\t\t\t\t            \t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"board_box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><h3>대외활동</h3></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ol id=\"ea_title\">\r\n");
      out.write("\t\t\t\t\t\t");
 if(externalList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"area_title\">조회된 리스트가 없습니다.</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else if(externalList.size() >= 3) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < 4; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 Board b = externalList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"enroll\" type=\"hidden\" value=\"");
      out.print(b.getEnrollState() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (Board b : externalList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"enroll\" type=\"hidden\" value=\"");
      out.print(b.getEnrollState() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t        $(function(){\r\n");
      out.write("\t\t\t\t\t            $('#ea_title .area_list').mouseenter(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css({'cursor':'pointer'});\r\n");
      out.write("\t\t\t\t\t            }).mouseout(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css('none');\r\n");
      out.write("\t\t\t\t\t            }).click(function(){\r\n");
      out.write("\t\t\t\t\t            \tvar bId = $(this).parent().children('input').val();\r\n");
      out.write("\t\t\t\t\t                var enroll = $(this).parent().children('#enroll').val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(enroll == 'N'){\r\n");
      out.write("\t\t\t\t\t            \t\tlocation.href = '");
      out.print(request.getContextPath());
      out.write("/eaDetail.cm?bId=' + bId;\r\n");
      out.write("\t\t\t\t\t            \t} else {\r\n");
      out.write("\t\t\t\t\t            \t\tlocation.href = '");
      out.print(request.getContextPath());
      out.write("/detail.ea?bId='+ bId;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"board_area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"board_box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><h3>자유게시판</h3></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ol id=\"coomu_title\">\r\n");
      out.write("\t\t\t\t\t\t");
 if(commuFreeList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"area_title\">조회된 리스트가 없습니다.</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else if(commuFreeList.size() >= 3) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < 4; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 Board b = commuFreeList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (Board b : commuFreeList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t        $(function(){\r\n");
      out.write("\t\t\t\t\t            $('#coomu_title .area_list').mouseenter(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css({'cursor':'pointer'});\r\n");
      out.write("\t\t\t\t\t            }).mouseout(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css('none');\r\n");
      out.write("\t\t\t\t\t           \t}).click(function(){\r\n");
      out.write("\t\t\t\t\t           \t \tvar bId = $(this).parent().children('input').val();\r\n");
      out.write("\t\t\t\t\t\t       \t \tlocation.href = '");
      out.print(request.getContextPath());
      out.write("/fDetail.cm?bId='+bId;\r\n");
      out.write("\t\t\t\t\t           \t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"board_box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><h3>Q / A</h3></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ol id=\"qa_title\">\r\n");
      out.write("\t\t\t\t\t\t");
 if(qaList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"area_title\">조회된 리스트가 없습니다.</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else if(qaList.size() >= 3) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < 4; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 Board b = qaList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (Board b : qaList) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"area_list\">");
      out.print( b.getBoardTitle() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.print( b.getBoardCreateDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t<script>\r\n");
      out.write("        \t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t            $('#qa_title .area_list').mouseenter(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css({'cursor':'pointer'});\r\n");
      out.write("\t\t\t\t\t            }).mouseout(function(){\r\n");
      out.write("\t\t\t\t\t               $(this).css('none');\r\n");
      out.write("\t\t\t\t\t            }).click(function(){\r\n");
      out.write("\t\t\t\t\t            \tvar bId = $(this).parent().children('input').val();\r\n");
      out.write("\t\t\t\t\t                  location.href = '");
      out.print(request.getContextPath());
      out.write("/q_detail.qa?bId='+ bId;\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("hr {\r\n");
      out.write("  color: black;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  height: 1px;\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  border: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding-top: 10px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 3%;\r\n");
      out.write("  padding-top: 3%;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_box {\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  color: rgb(255, 213, 0);\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<footer>\r\n");
      out.write("   <div class=\"footer_box\">\r\n");
      out.write("      Copyrightⓒ2020 Flower than java Project All Rights Reserved.\r\n");
      out.write("   </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t   var fileTarget = $('.filebox .upload-hidden');\r\n");
      out.write("\r\n");
      out.write("\t\t    fileTarget.on('change', function(){\r\n");
      out.write("\t\t        if(window.FileReader){\r\n");
      out.write("\t\t            // 파일명 추출\r\n");
      out.write("\t\t            var filename = $(this)[0].files[0].name;\r\n");
      out.write("\t\t        } \r\n");
      out.write("\r\n");
      out.write("\t\t        else {\r\n");
      out.write("\t\t            // Old IE 파일명 추출\r\n");
      out.write("\t\t            var filename = $(this).val().split('/').pop().split('\\\\').pop();\r\n");
      out.write("\t\t        };\r\n");
      out.write("\r\n");
      out.write("\t\t        $(this).siblings('.upload-name').val(filename);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\r\n");
      out.write("\t\t    //preview image \r\n");
      out.write("\t\t    var imgTarget = $('.preview-image .upload-hidden');\r\n");
      out.write("\r\n");
      out.write("\t\t    imgTarget.on('change', function(){\r\n");
      out.write("\t\t        var parent = $(this).parent();\r\n");
      out.write("\t\t        parent.children('.upload-display').remove();\r\n");
      out.write("\r\n");
      out.write("\t\t        if(window.FileReader){\r\n");
      out.write("\t\t            //image 파일만\r\n");
      out.write("\t\t            if (!$(this)[0].files[0].type.match(/image\\//)) return;\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            var reader = new FileReader();\r\n");
      out.write("\t\t            reader.onload = function(e){\r\n");
      out.write("\t\t                var src = e.target.result;\r\n");
      out.write("\t\t                parent.prepend('<div class=\"upload-display\"><div class=\"upload-thumb-wrap\"><img src=\"'+src+'\" class=\"upload-thumb\"></div></div>');\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            reader.readAsDataURL($(this)[0].files[0]);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\r\n");
      out.write("\t\t        else {\r\n");
      out.write("\t\t            $(this)[0].select();\r\n");
      out.write("\t\t            $(this)[0].blur();\r\n");
      out.write("\t\t            var imgSrc = document.selection.createRange().text;\r\n");
      out.write("\t\t            parent.prepend('<div class=\"upload-display\"><div class=\"upload-thumb-wrap\"><img class=\"upload-thumb\"></div></div>');\r\n");
      out.write("\r\n");
      out.write("\t\t            var img = $(this).siblings('.upload-display').find('img');\r\n");
      out.write("\t\t            img[0].style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(enable='true',sizingMethod='scale',src=\\\"\"+imgSrc+\"\\\")\";        \r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t});\r\n");
      out.write(" \r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
