/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-10 02:30:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 메인페이지_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/headerfooter.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/maincontents.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header_top\">\r\n");
      out.write("         <div class=\"top\">\r\n");
      out.write("            <li><a href=\"#\" class=\"top_btn\"><b>마이페이지</b></a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"top_btn\"><b>로그인</b></a></li>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"navbar\">\r\n");
      out.write("         <div class=\"navbar_title\">\r\n");
      out.write("            <a href=\"#\"><font size =\"7\">정</font>부지원금<font size =\"7\">바</font>로 지금</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_menu\">\r\n");
      out.write("            <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"#\">지원정책</a></li>\r\n");
      out.write("            <li><a href=\"#\">커뮤니티</a></li>\r\n");
      out.write("            <li><a href=\"#\">대외활동</a></li>\r\n");
      out.write("            <li><a href=\"#\">Q / A</a></li>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_logo\">\r\n");
      out.write("            <img id=\"logo\" src=\"../Media/logo.png\" width = \"80px\" height = \"80px\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("   </header> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"contents\">\r\n");
      out.write("<!-- 이미지 슬라이더 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("   <div class=\"swiper-container\">\r\n");
      out.write("      <div class=\"swiper-wrapper\">\r\n");
      out.write("         <div class=\"swiper-slide\" ><img src=\"http://oldmidi.cdn3.cafe24.com/p/0315.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0316.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0067.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0423.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"https://ktsmemo.cafe24.com/p/0074.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0637.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0348.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0824.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0764.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0239.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0804.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://oldmidi.cdn3.cafe24.com/p/0441.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"http://ktsmemo.cdn3.cafe24.com/p/0178.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"https://ktsmemo.cafe24.com/p/0454.jpg\"></div>\r\n");
      out.write("         <div class=\"swiper-slide\"><img src=\"https://ktsmemo.cafe24.com/p/0187.jpg\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("      <!-- 네비게이션 -->\r\n");
      out.write("      <div class=\"swiper-button-next\"></div><!-- 다음 버튼 (오른쪽에 있는 버튼) -->\r\n");
      out.write("      <div class=\"swiper-button-prev\"></div><!-- 이전 버튼 -->\r\n");
      out.write("   \r\n");
      out.write("      <!-- 페이징 -->\r\n");
      out.write("      <div class=\"swiper-pagination\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 이미지 슬라이더 -->\r\n");
      out.write("   <div class=\"util_area\">\r\n");
      out.write("      <div class=\"notice_util_area\" >\r\n");
      out.write("         <div class=\"list_type_a\">\r\n");
      out.write("               <div class=\"area_title\">\r\n");
      out.write("                  <a href=\"#\"><h3>공지사항</h3></a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">공지사항 최신글1</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">공지사항 최신글2</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">공지사항 최신글3</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">공지사항 최신글4</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"policy_util_area\" >\r\n");
      out.write("      <div class=\"list_type_a\">\r\n");
      out.write("            <div class=\"area_title\">\r\n");
      out.write("               <a href=\"#\"><h3>지원정책</h3></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">지원정책 최신글1</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">지원정책 최신글2</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">지원정책 최신글3</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">지원정책 최신글4</a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"community_util_area\" >\r\n");
      out.write("      <div class=\"list_type_b\">\r\n");
      out.write("            <div class=\"area_title\">\r\n");
      out.write("               <a href=\"#\"><h3>커뮤니티</h3></a>\r\n");
      out.write("               <div class=\"all_link_area\">\r\n");
      out.write("                  <a href=\"#\">커뮤니티1</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">커뮤니티2</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">커뮤니티3</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">커뮤니티4</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글1</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글2</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글3</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글4</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글5</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글6</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글7</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">커뮤니티 최신글8</a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"external_util_area\" >\r\n");
      out.write("      <div class=\"list_type_b\">\r\n");
      out.write("            <div class=\"area_title\">\r\n");
      out.write("               <a href=\"#\"><h3>대외활동</h3></a>\r\n");
      out.write("               <div class=\"all_link_area\">\r\n");
      out.write("                  <a href=\"#\">대외활동</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">대외활동</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">대외활동</a>\r\n");
      out.write("                  <span class=\"text_bar\">|</span>\r\n");
      out.write("                  <a href=\"#\">대외활동</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글1</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글2</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글3</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글4</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글5</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글6</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글7</a>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">대외활동 최신글8</a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <br clear=\"all\">\r\n");
      out.write("   <div id=\"mySerach\" align = \"middle\">\r\n");
      out.write("        <h3><p align = \"left\" style=\"padding-left: 30px;\">나를 위한 지원금 찾기</p></h3>   \r\n");
      out.write("        <div align =\"left\">\r\n");
      out.write("           <span  class=\"mySerach\"> <b>나이</b> <input type=\"number\" min=1 width=\"\"></span>\r\n");
      out.write("        <select id = \"gender\" class=\"mySerach\" > \r\n");
      out.write("            <option value=\"1\">남</option>\r\n");
      out.write("            <option value=\"2\">여</option>\r\n");
      out.write("        </select> \r\n");
      out.write("        <select id = \"location\" class=\"mySerach\">\r\n");
      out.write("            <option value=\"1\">가평군</option>\r\n");
      out.write("            <option value=\"2\">고양시</option>\r\n");
      out.write("            <option value=\"3\">과천시</option>\r\n");
      out.write("            <option value=\"4\">광명시</option>\r\n");
      out.write("            <option value=\"5\">광주시</option>\r\n");
      out.write("            <option value=\"6\">구리시</option>\r\n");
      out.write("            <option value=\"7\">군포시</option>\r\n");
      out.write("            <option value=\"8\">김포시</option>\r\n");
      out.write("            <option value=\"9\">남양주시</option>\r\n");
      out.write("            <option value=\"10\">동두천시</option>\r\n");
      out.write("            <option value=\"11\">부천시</option>\r\n");
      out.write("            <option value=\"12\">성남시</option>\r\n");
      out.write("            <option value=\"13\">수원시</option>\r\n");
      out.write("            <option value=\"14\">시흥시</option>\r\n");
      out.write("            <option value=\"15\">안산시</option>\r\n");
      out.write("            <option value=\"16\">안성시</option>\r\n");
      out.write("            <option value=\"17\">안양시</option>\r\n");
      out.write("            <option value=\"18\">양주시</option>\r\n");
      out.write("            <option value=\"19\">양평군</option>\r\n");
      out.write("            <option value=\"20\">여주시</option>\r\n");
      out.write("            <option value=\"21\">연천군</option>\r\n");
      out.write("            <option value=\"22\">오산시</option>\r\n");
      out.write("            <option value=\"23\">용인시</option>\r\n");
      out.write("            <option value=\"24\">의왕시</option>\r\n");
      out.write("            <option value=\"25\">의정부시</option>\r\n");
      out.write("            <option value=\"26\">이천시</option>\r\n");
      out.write("            <option value=\"27\">파주시</option>\r\n");
      out.write("            <option value=\"28\">평택시</option>\r\n");
      out.write("            <option value=\"29\">포천시</option>\r\n");
      out.write("            <option value=\"30\">하남시</option>\r\n");
      out.write("            <option value=\"31\">화성시</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <button onclick=\"search();\">검색</button>\r\n");
      out.write("        </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("   </div>\r\n");
      out.write("   <hr>\r\n");
      out.write("   <footer>\r\n");
      out.write("      <div class=\"footer_box\">\r\n");
      out.write("         Copyrightⓒ2020 Flower than java Project All Rights Reserved.\r\n");
      out.write("      </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 이미지 슬라이더\r\n");
      out.write("   new Swiper('.swiper-container', {\r\n");
      out.write("   \r\n");
      out.write("      slidesPerView : 3, // 동시에 보여줄 슬라이드 갯수\r\n");
      out.write("      spaceBetween : 30, // 슬라이드간 간격\r\n");
      out.write("      slidesPerGroup : 3, // 그룹으로 묶을 수, slidesPerView 와 같은 값을 지정하는게 좋음\r\n");
      out.write("   \r\n");
      out.write("      // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("      // 3개가 나와야 되는데 1개만 있다면 2개는 빈칸으로 채워서 3개를 만듬\r\n");
      out.write("      loopFillGroupWithBlank : true,\r\n");
      out.write("   \r\n");
      out.write("      loop : true, // 무한 반복\r\n");
      out.write("   \r\n");
      out.write("      pagination : { // 페이징\r\n");
      out.write("         el : '.swiper-pagination',\r\n");
      out.write("         clickable : true, // 페이징을 클릭하면 해당 영역으로 이동, 필요시 지정해 줘야 기능 작동\r\n");
      out.write("      },\r\n");
      out.write("      navigation : { // 네비게이션\r\n");
      out.write("         nextEl : '.swiper-button-next', // 다음 버튼 클래스명\r\n");
      out.write("         prevEl : '.swiper-button-prev', // 이번 버튼 클래스명\r\n");
      out.write("      },\r\n");
      out.write("   });\r\n");
      out.write("// 이미지 슬라이더\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
