/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-04 10:30:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.External_005fActivities;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.Board;
import java.util.ArrayList;
import member.model.vo.Member;
import board.model.vo.PageInfo;

public final class 대외활동검색메인_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/External_Activities/../Common/header.jsp", Long.valueOf(1598772679072L));
    _jspx_dependants.put("/WEB-INF/views/External_Activities/../Common/footer.jsp", Long.valueOf(1598887312249L));
    _jspx_dependants.put("/WEB-INF/views/External_Activities/../Common/page.jsp", Long.valueOf(1599207817910L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.PageInfo");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 ArrayList<Board> list = (ArrayList<Board>)request.getAttribute("list"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>게시판 기본틀</title>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/body.css\">\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(" section{\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  .writertext{\r\n");
      out.write("      line-height: 70px;\r\n");
      out.write("      list-style: none;\r\n");
      out.write("  }\r\n");
      out.write("    .serach_box{\r\n");
      out.write("    \tfloat:rights;\r\n");
      out.write("        background-color: RGB(248,248,248);\r\n");
      out.write("        display: flex;\r\n");
      out.write("    }\r\n");
      out.write("    .select_box{\r\n");
      out.write("        margin: 16px;\r\n");
      out.write("        line-height: 70px;\r\n");
      out.write("    }\r\n");
      out.write("    .select_btn{\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        background-color:  RGB(221,228,236);\r\n");
      out.write("    }\r\n");
      out.write("    .categoty_select{\r\n");
      out.write("        height: 40px;\r\n");
      out.write("    }\r\n");
      out.write("    .result_btn{\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        margin-right: 30px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.min.js\"></script> \r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("header {\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".header_top {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write(".top {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  float: right;\r\n");
      out.write("  padding-right: 10%;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding-top: 4px;\r\n");
      out.write("}\r\n");
      out.write(".top_btn {\r\n");
      out.write("  margin: 1px;\r\n");
      out.write("  padding: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".top_btn:hover {\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".lagefont {\r\n");
      out.write("  font-size: 60px;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_dropdown:hover .navbar_dropdown-content {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  background-color: #f9f9f9;\r\n");
      out.write("  min-width: 100px;\r\n");
      out.write("  max-width: 100px;\r\n");
      out.write("  box-shadow: 0px 0px 0px 2px rgba(0,0,0,0.2);\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 5px 6px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-table;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a:hover{\r\n");
      out.write("\t background-color: #f5f5f5;\r\n");
      out.write("  \tfont-weight: bold;\r\n");
      out.write("  \tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_menu {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding: 40px 0px;\r\n");
      out.write("  padding-right: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li {\r\n");
      out.write("  border-right: 1px solid silver;\r\n");
      out.write("  padding: 8px 12px; /* 마우스 선택영역이 넓어짐 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li:hover {\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("header {\r\n");
      out.write("  height: auto;\r\n");
      out.write("}\r\n");
      out.write("  .navbar {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .navbar_title {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 0px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu li {\r\n");
      out.write("    border-right: 0px solid silver;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    padding: 8px 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .top {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_logo img {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header_top\">\r\n");
      out.write("         <div class=\"top\">\r\n");
      out.write("         ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/insertForm.me\" class=\"top_btn\"><b>회원가입</b></a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/loginPage.me\" class=\"top_btn\"><b>로그인</b></a></li>\r\n");
      out.write("         ");
 } else { 
      out.write("\r\n");
      out.write("         \t<li><label>");
      out.print( loginUser.getMemberName() );
      out.write("님의 방문을 환영합니다.</label></li>\r\n");
      out.write("         \t");
 if(loginUser.getMemberName().equals("관리자")) { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage.ad\" class=\"top_btn\"><b>관리자 페이지</b></a></li>\r\n");
      out.write("         \t");
 } else { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage.me\" class=\"top_btn\"><b>마이페이지</b></a></li>\r\n");
      out.write("        \t ");
 } 
      out.write("\r\n");
      out.write("         \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" class=\"top_btn\"><b>로그아웃</b></a></li>\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     <nav class=\"navbar\">\r\n");
      out.write("         <div class=\"navbar_title\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("\"><span class=\"lagefont\">정</span>부지원금<span class=\"lagefont\">바</span>로 지금</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_menu\">\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.no\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.sp\">지원정책</a></li>\r\n");
      out.write("             <li class=\"navbar_dropdown\">\r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\" class=\"navbar_dropbtn\">커뮤니티</a>\r\n");
      out.write("             <div class='navbar_dropdown-content'>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\">자유게시판</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/spMain.cm\">지원정책</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/eaMain.cm\">대외활동</a>\r\n");
      out.write("             </div>\r\n");
      out.write("           </li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.ea\">대외활동</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.fa\">묻고 답하기</a></li>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_logo\">\r\n");
      out.write("            <img id=\"logo\" src=\"Media/logo.png\" width = \"80px\" height = \"80px\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("   </header> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write(" <!----------------------------------------header------------------------------------------->\r\n");
      out.write("    <section>\r\n");
      out.write("            <h1 align=\"center\">대외활동 검색</h1>\r\n");
      out.write("\t<div class=\"serach_box\">\r\n");
      out.write("      <ul class=\"writertext\">\r\n");
      out.write("          <th>\r\n");
      out.write("              <li><h3>카테고리</h3></li>\r\n");
      out.write("              <li><h3>대상</h3></li>\r\n");
      out.write("              <li><h3>지역</h3></li>\r\n");
      out.write("          </th>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- 대외활동 글쓰기 카테고리,대상,지역별 선택 -->\r\n");
      out.write("      <div class=\"select_box\">\r\n");
      out.write("          <h6>\r\n");
      out.write("              <select class=\"categoty_select\" name=\"ea_category\">\r\n");
      out.write("                  <option value=\"선택\" selected disabled hidden >선택</option>\r\n");
      out.write("                  <option value=\"공모전\">공모전</option>\r\n");
      out.write("                  <option value=\"채용박람회/취업박람회\">채용박람회/취업박람회</option>\r\n");
      out.write("                  <option value=\"경진대회\">경진대회</option>\r\n");
      out.write("                  <option value=\"봉사활동\">봉사활동</option>\r\n");
      out.write("                  <option value=\"서포터즈\">서포터즈</option>\r\n");
      out.write("                  <option value=\"관람/전시/체험\">관람/전시/체험</option>\r\n");
      out.write("              </select>\r\n");
      out.write("          </h6>\r\n");
      out.write("          <h6>\r\n");
      out.write("              <div>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"ea_age_18\">청년<br>(18~34세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"ea_age_35\">중년<br>(35~49세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"ea_age_50\">장년<br>(50~64세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"ea_age_65\">어르신<br>(65세 이상) </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"ck_ea_age\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_ea_age\" id=\"ck_ea_age_18\" value=\"청년\"\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_ea_age\" id=\"ck_ea_age_35\" value=\"중년\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_ea_age\" id=\"ck_ea_age_50\" value=\"장년\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_ea_age\" id=\"ck_ea_age_65\" value=\"어르신\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("               $(function(){\r\n");
      out.write("                  $(\"#ck_ea_age\").hide();\r\n");
      out.write("                  $(\"#ea_age_18\").click(function(){\r\n");
      out.write("                     $(\"#ck_ea_age_18\").click();\r\n");
      out.write("                     if($(\"#ck_ea_age_18\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#ea_age_35\").click(function(){\r\n");
      out.write("                     $(\"#ck_ea_age_35\").click();\r\n");
      out.write("                     if($(\"#ck_ea_age_35\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#ea_age_50\").click(function(){\r\n");
      out.write("                     $(\"#ck_ea_age_50\").click();\r\n");
      out.write("                     if($(\"#ck_ea_age_50\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#ea_age_65\").click(function(){\r\n");
      out.write("                     $(\"#ck_ea_age_65\").click();\r\n");
      out.write("                     if($(\"#ck_ea_age_65\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("               });\r\n");
      out.write("           </script>\r\n");
      out.write("          </h6>\r\n");
      out.write("          <h6 id = \"ea_areatable_div\">\r\n");
      out.write("              <div id= \"ea_areatable\">\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GP\">가평군</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GY\">고양시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GC\">과천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GM\">광명시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GJ\">광주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GL\">구리시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GP2\">군포시</button>\r\n");
      out.write("\t              <br>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"GP3\">김포시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"NYJ\">남양주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"DDC\">동두천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"BC\">부천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"SN\">성남시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"SW\">수원시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"SH\">시흥시</button>\r\n");
      out.write("\t              <br>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"AS\">안산시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"AY\">안양시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"PJ\">파주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"PT\">평택시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"PC\">포천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"HN\">하남시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id= \"HS\">화성시</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"ck_ea_areatable\">\r\n");
      out.write("             \t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP\" value=\"가평군\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GY\" value=\"고양시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GC\" value=\"과천시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GM\" value=\"광명시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GJ\" value=\"광주시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GL\" value=\"구리시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP2\" value=\"군포시\">\r\n");
      out.write("              \t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP3\" value=\"김포시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_NYJ\" value=\"남양주시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_DDC\" value=\"동두천시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_BC\" value=\"부천시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SN\" value=\"성남시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SW\" value=\"수원시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SH\" value=\"시흥시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_AS\" value=\"안산시\"\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_AY\" value=\"안양시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PJ\" value=\"파주시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PT\" value=\"평택시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PC\" value=\"포천시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_HN\" value=\"하남시\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_HS\" value=\"화성시\">\r\n");
      out.write("            </div>\r\n");
      out.write("             <script>\r\n");
      out.write("               $(function(){\r\n");
      out.write("                  $(\"#ck_ea_areatable\").hide();\r\n");
      out.write("                  $(\"#GP\").click(function(){\r\n");
      out.write("                     $(\"#ck_GP\").click();\r\n");
      out.write("                     if($(\"#ck_GP\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#GY\").click(function(){\r\n");
      out.write("                      $(\"#ck_GY\").click();\r\n");
      out.write("                      if($(\"#ck_GY\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GC\").click(function(){\r\n");
      out.write("                      $(\"#ck_GC\").click();\r\n");
      out.write("                      if($(\"#ck_GC\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GM\").click(function(){\r\n");
      out.write("                      $(\"#ck_GM\").click();\r\n");
      out.write("                      if($(\"#ck_GM\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GJ\").click(function(){\r\n");
      out.write("                      $(\"#ck_GJ\").click();\r\n");
      out.write("                      if($(\"#ck_GJ\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GL\").click(function(){\r\n");
      out.write("                      $(\"#ck_GL\").click();\r\n");
      out.write("                      if($(\"#ck_GL\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GP2\").click(function(){\r\n");
      out.write("                      $(\"#ck_GP2\").click();\r\n");
      out.write("                      if($(\"#ck_GP2\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GP3\").click(function(){\r\n");
      out.write("                      $(\"#ck_GP3\").click();\r\n");
      out.write("                      if($(\"#ck_GP3\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                   $(\"#NYJ\").click(function(){\r\n");
      out.write("                       $(\"#ck_NYJ\").click();\r\n");
      out.write("                       if($(\"#ck_NYJ\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#DDC\").click(function(){\r\n");
      out.write("                       $(\"#ck_DDC\").click();\r\n");
      out.write("                       if($(\"#ck_DDC\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#BC\").click(function(){\r\n");
      out.write("                       $(\"#ck_BC\").click();\r\n");
      out.write("                       if($(\"#ck_BC\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SN\").click(function(){\r\n");
      out.write("                       $(\"#ck_SN\").click();\r\n");
      out.write("                       if($(\"#ck_SN\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SW\").click(function(){\r\n");
      out.write("                       $(\"#ck_SW\").click();\r\n");
      out.write("                       if($(\"#ck_SW\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SH\").click(function(){\r\n");
      out.write("                       $(\"#ck_SH\").click();\r\n");
      out.write("                       if($(\"#ck_SH\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#AS\").click(function(){\r\n");
      out.write("                       $(\"#ck_AS\").click();\r\n");
      out.write("                       if($(\"#ck_AS\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#AY\").click(function(){\r\n");
      out.write("                        $(\"#ck_AY\").click();\r\n");
      out.write("                        if($(\"#ck_AY\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PJ\").click(function(){\r\n");
      out.write("                        $(\"#ck_PJ\").click();\r\n");
      out.write("                        if($(\"#ck_PJ\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PT\").click(function(){\r\n");
      out.write("                        $(\"#ck_PT\").click();\r\n");
      out.write("                        if($(\"#ck_PT\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PC\").click(function(){\r\n");
      out.write("                        $(\"#ck_PC\").click();\r\n");
      out.write("                        if($(\"#ck_PC\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#HN\").click(function(){\r\n");
      out.write("                        $(\"#ck_HN\").click();\r\n");
      out.write("                        if($(\"#ck_HN\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#HS\").click(function(){\r\n");
      out.write("                        $(\"#ck_HS\").click();\r\n");
      out.write("                        if($(\"#ck_HS\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("               });\r\n");
      out.write("           </script>\r\n");
      out.write("          </h6>\r\n");
      out.write("      </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br clear=\"all\">\t    \r\n");
      out.write("      <div class = \"sp_button\">\r\n");
      out.write("\t\t<input type='button' class='result_btn' name='btn' value='초기화' style=\"float: right;\" id=\"p_sp_search_reset\">\r\n");
      out.write("\t\t<input type='button' class='result_btn' id='btnSearch' name='btn' value='검색' style=\"float: right;\" id=\"p_sp_search_submit\" onclick=\"location.href='");
      out.print( request.getContextPath()  );
      out.write("/search.ea'\">\r\n");
      out.write("\t</div>  \r\n");
      out.write("                    <!-- 대외활동 글쓰기 카테고리,대상,지역별 선택 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"result_table\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 
    
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	System.out.println(pi);
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();	
	String pageName = pi.getPageName();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .pagingArea button{background: white; border: 0; outline: 0; margin: 1px;}\r\n");
      out.write("\tbutton:hover{cursor: pointer;}\r\n");
      out.write("\t#numBtn{background: rgb(15, 76, 130); color: white; border-radius: 7px; width: 40px; heigth: 40px; padding: 5px 0px;}\r\n");
      out.write("\t#choosen{background: skyblue; color: white; width: 40px; border-radius: 7px; padding: 5px 0px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--  페이징 -->\r\n");
      out.write("\t<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t\t<!-- 맨처음으로 -->\r\n");
      out.write("\t\t<button class=\"paginbtn\" onclick=\"location.href='");
      out.print( request.getContextPath()+pageName );
      out.write("?currentPage=1'\" id=\"firstBtn\">처음</button>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif(");
      out.print( currentPage );
      out.write(" <=1){\r\n");
      out.write("\t\t\t\tvar before = $('#firstBtn');\r\n");
      out.write("\t\t\t\tbefore.attr('disabled', 'true');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- 이전 페이지로 -->\r\n");
      out.write("\t\t<button class=\"paginbtn\" onclick=\"location.href='");
      out.print( request.getContextPath()+pageName );
      out.write("?currentPage=");
      out.print( currentPage - 1 );
      out.write("'\" id=\"beforeBtn\">이전</button>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif(");
      out.print( currentPage );
      out.write(" <=1){\r\n");
      out.write("\t\t\t\tvar before = $('#beforeBtn');\r\n");
      out.write("\t\t\t\tbefore.attr('disabled', 'true');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- 10개 페이지 목록 -->\r\n");
      out.write("\t\t");
 for(int p = startPage; p<= endPage; p++){ 
      out.write("\r\n");
      out.write("\t\t\t");
 if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t<button id=\"choosen\" disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<button id=\"numBtn\" onclick=\"location.href='");
      out.print( request.getContextPath()+pageName );
      out.write("?currentPage=");
      out.print( p );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t<!-- 다음 페이지로 -->\r\n");
      out.write("\t\t<button class=\"paginbtn\" onclick=\"location.href='");
      out.print( request.getContextPath()+pageName );
      out.write("?currentPage=");
      out.print( currentPage + 1 );
      out.write("'\" id=\"afterBtn\">다음</buuton>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif(");
      out.print( currentPage );
      out.write(" >= ");
      out.print( maxPage );
      out.write("){\r\n");
      out.write("\t\t\t\tvar after = $('#afterBtn');\r\n");
      out.write("\t\t\t\tafter.attr('disabled','true');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 맨 끝으로 -->\r\n");
      out.write("\t\t<button class=\"paginbtn\" onclick=\"location.href='");
      out.print( request.getContextPath()+pageName );
      out.write("?currentPage=");
      out.print( maxPage );
      out.write("'\" id=\"lastBtn\">맨끝</button>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif(");
      out.print( currentPage );
      out.write(" >= ");
      out.print( maxPage );
      out.write("){\r\n");
      out.write("\t\t\t\tvar after = $('#lastBtn');\r\n");
      out.write("\t\t\t\tafter.attr('disabled','true');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("hr {\r\n");
      out.write("  color: black;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  height: 1px;\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  border: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding-top: 10px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 3%;\r\n");
      out.write("  padding-top: 3%;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_box {\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  color: rgb(255, 213, 0);\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<footer>\r\n");
      out.write("   <div class=\"footer_box\">\r\n");
      out.write("      Copyrightⓒ2020 Flower than java Project All Rights Reserved.\r\n");
      out.write("   </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
