/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-11 05:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import board.model.vo.*;
import member.model.vo.Member;

public final class 지원정책글수정_0028커뮤니티_0029_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/Community/../Common/header.jsp", Long.valueOf(1599364317178L));
    _jspx_dependants.put("/WEB-INF/views/Community/../Common/footer.jsp", Long.valueOf(1599750369908L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Board b = (Board)request.getAttribute("board"); 

	System.out.println("지원커뮤_글수정 에서의 Board : " + b);	
	
	ArrayList<FileVO> fList = (ArrayList<FileVO>)request.getAttribute("fileList");
	FileVO titleImg = fList.get(0);
	String categoryStr = b.getCgName();
	String[] categoryarr = new String[7];
	String[] splitCate = categoryStr.split(",");
	for(int i = 0; i < splitCate.length; i++){
		switch(splitCate[i]){
		case "선택" : categoryarr[0] = "selected"; break; 
		case "재직지원" : categoryarr[1] = "selected"; break; 
		case "취업지원" : categoryarr[2] = "selected"; break; 
		case "기업지원" : categoryarr[3] = "selected"; break; 
		case "창업지원" : categoryarr[4] = "selected"; break; 
		case "생활/금융" : categoryarr[5] = "selected"; break; 
		case "교통/주거" : categoryarr[6] = "selected"; break; 
		 
		}
	}
	
	String emState = b.getEmState();
	String[] emStatearr = new String[2];
	String[] splitEmState = emState.split(",");
	for(int i = 0; i< splitEmState.length; i++){
		switch(splitEmState[i]){
		case "재직중":emStatearr[0] = "checked"; break;
		case "구직중":emStatearr[1] = "checked"; break;
		}
	}
	
	String tcName = b.getTcName();
	String[] tcarr = new String[4];
	String[] splitTc = tcName.split(",");
	for(int i = 0; i < splitTc.length; i++){
		switch(splitTc[i]){
		case "청년": tcarr[0] = "checked"; break;
		case "중년": tcarr[1] = "checked"; break;
		case "장년": tcarr[2] = "checked"; break;
		case "어르신": tcarr[3] = "checked"; break;
		}
	}
	
	String lcName = b.getLcName();
	String[] lcarr = new String[21];
	String[] splitLc = lcName.split(",");
	for(int i = 0; i < splitLc.length; i++){
		switch(splitLc[i]){
		case "가평군": lcarr[0] = "checked"; break;
		case "고양시": lcarr[1] = "checked"; break;
		case "과천시": lcarr[2] = "checked"; break;
		case "광명시": lcarr[3] = "checked"; break;
		case "광주시": lcarr[4] = "checked"; break;
		case "구리시": lcarr[5] = "checked"; break;
		case "군포시": lcarr[6] = "checked"; break;
		case "김포시": lcarr[7] = "checked"; break;
		case "남양주시": lcarr[8] = "checked";break;
		case "동두천시": lcarr[9] = "checked";break;
		case "부천시": lcarr[10] = "checked"; break;
		case "성남시": lcarr[11] = "checked"; break;
		case "수원시": lcarr[12] = "checked"; break;
		case "시흥시": lcarr[13] = "checked"; break;
		case "안산시": lcarr[14] = "checked"; break;
		case "안양시": lcarr[15] = "checked"; break;
		case "파주시": lcarr[16] = "checked"; break;
		case "평택시": lcarr[17] = "checked"; break;
		case "포천시": lcarr[18] = "checked"; break;
		case "하남시": lcarr[19] = "checked"; break;
		case "화성시": lcarr[20] = "checked"; break;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>정부지원금 바로지금</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/body.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmin-width: 505px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lagefont {\r\n");
      out.write("\tcolor: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tfont-family: \"fantasy\";\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmin-height: 80%;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside {\r\n");
      out.write("\tmin-height: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main_section {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmin-height: 100%;\r\n");
      out.write("\tmargin: 0px 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tborder: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a{\r\n");
      out.write("    padding: 8px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    color: black;\r\n");
      out.write("    border-radius : 3px;\r\n");
      out.write("}    \r\n");
      out.write(".pagination a:hover:not(.action){\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* pagination 설정부  */\r\n");
      out.write(".com{text-indent : 20px;}\r\n");
      out.write("\r\n");
      out.write(" \t.btn{\r\n");
      out.write("  \t\tbackground-color : #E3F2FD;\r\n");
      out.write("  \t\tmargin : 10px 2px;\r\n");
      out.write("  \t\tpadding: 10px;\r\n");
      out.write("  \t}\r\n");
      out.write(".contentsTable{text-align:center; font-size:12pt;}\r\n");
      out.write(".contentsTable thead{background-color:rgb(15, 76, 130); color:white;}\r\n");
      out.write(".contentsTable tbody{background-color:#F7F7F7}\r\n");
      out.write("#tablename{align-self:center;}\r\n");
      out.write("#게시판이름{text-align:center;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("      display: block;\r\n");
      out.write("  }\r\n");
      out.write("  .writerinformanion_box{\r\n");
      out.write("      background-color: RGB(248,248,248);\r\n");
      out.write("      display: flex;\r\n");
      out.write("  }\r\n");
      out.write("  .writertext{\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      line-height: 70px;\r\n");
      out.write("  }\r\n");
      out.write("  .select_box{\r\n");
      out.write("      margin: 16px;\r\n");
      out.write("      line-height: 70px;\r\n");
      out.write("  }\r\n");
      out.write("  .select_btn{\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      width: 100px;\r\n");
      out.write("      background-color:  RGB(221,228,236);\r\n");
      out.write("  }\r\n");
      out.write("  .categoty_select{\r\n");
      out.write("      height: 40px;\r\n");
      out.write("  }\r\n");
      out.write("  .writer_box{\r\n");
      out.write("      margin: 0px auto;\r\n");
      out.write("  }\r\n");
      out.write("  .writer_table{\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    line-height: 80px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .writer_text{\r\n");
      out.write("      margin-left: 80px;\r\n");
      out.write("      line-height: 160px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("  textarea{\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    resize: none;\r\n");
      out.write("  }\r\n");
      out.write("  .textline1{\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .sp_button{\r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .result_btn{\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    margin: 30px;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.min.js\"></script> \r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("header {\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".header_top {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write(".top {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  float: right;\r\n");
      out.write("  padding-right: 10%;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding-top: 4px;\r\n");
      out.write("}\r\n");
      out.write(".top_btn {\r\n");
      out.write("  margin: 1px;\r\n");
      out.write("  padding: 4px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".top_btn:hover {\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".lagefont {\r\n");
      out.write("  font-size: 60px;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_dropdown:hover .navbar_dropdown-content {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  background-color: #f9f9f9;\r\n");
      out.write("  min-width: 100px;\r\n");
      out.write("  max-width: 100px;\r\n");
      out.write("  box-shadow: 0px 0px 0px 2px rgba(0,0,0,0.2);\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 5px 6px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-table;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".navbar_dropdown-content a:hover{\r\n");
      out.write("\t background-color: #f5f5f5;\r\n");
      out.write("  \tfont-weight: bold;\r\n");
      out.write("  \tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write(".navbar_menu {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding: 40px 0px;\r\n");
      out.write("  padding-right: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li {\r\n");
      out.write("  border-right: 1px solid silver;\r\n");
      out.write("  padding: 8px 12px; /* 마우스 선택영역이 넓어짐 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li:hover {\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("header {\r\n");
      out.write("  height: auto;\r\n");
      out.write("}\r\n");
      out.write("  .navbar {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .navbar_title {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 0px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_menu li {\r\n");
      out.write("    border-right: 0px solid silver;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    padding: 8px 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .top {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar_logo img {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header_top\">\r\n");
      out.write("         <div class=\"top\">\r\n");
      out.write("         ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/insertForm.me\" class=\"top_btn\"><b>회원가입</b></a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/loginPage.me\" class=\"top_btn\"><b>로그인</b></a></li>\r\n");
      out.write("         ");
 } else { 
      out.write("\r\n");
      out.write("         \t<li><label>");
      out.print( loginUser.getMemberName() );
      out.write("님의 방문을 환영합니다.</label></li>\r\n");
      out.write("         \t");
 if(loginUser.getMemberName().equals("관리자")) { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage.ad\" class=\"top_btn\"><b>관리자 페이지</b></a></li>\r\n");
      out.write("         \t");
 } else { 
      out.write("\r\n");
      out.write("         \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage.me\" class=\"top_btn\"><b>마이페이지</b></a></li>\r\n");
      out.write("        \t ");
 } 
      out.write("\r\n");
      out.write("         \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\" class=\"top_btn\"><b>로그아웃</b></a></li>\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     <nav class=\"navbar\">\r\n");
      out.write("         <div class=\"navbar_title\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Main.mi\"><span class=\"lagefont\">정</span>부지원금<span class=\"lagefont\">바</span>로 지금</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_menu\">\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.no\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.sp\">지원정책</a></li>\r\n");
      out.write("             <li class=\"navbar_dropdown\">\r\n");
      out.write("               <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\" class=\"navbar_dropbtn\">커뮤니티</a>\r\n");
      out.write("             <div class='navbar_dropdown-content'>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/fMain.cm\">자유게시판</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/spMain.cm\">지원정책</a><br>\r\n");
      out.write("                 <a href=\"");
      out.print( request.getContextPath() );
      out.write("/eaMain.cm\">대외활동</a>\r\n");
      out.write("             </div>\r\n");
      out.write("           </li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.ea\">대외활동</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.fa\">묻고 답하기</a></li>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"navbar_logo\">\r\n");
      out.write("            <img id=\"logo\" src=\"Media/logo.png\" width = \"80px\" height = \"80px\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("   </header> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" <!----------------------------------------header------------------------------------------->\r\n");
      out.write(" <section>\r\n");
      out.write(" <div id=\"main_section\">\r\n");
      out.write("  <form action=\"");
      out.print( request.getContextPath() );
      out.write("/spModify.cm\" method=\"post\" encType=\"multipart/form-data\">\r\n");
      out.write("    <h1 align=\"center\">지원정책 수정</h1>\r\n");
      out.write("    <div class=\"writerinformanion_box\">\r\n");
      out.write("      <ul class=\"writertext\">\r\n");
      out.write("          <th>\r\n");
      out.write("              <li class=\"infomation-item\"><h3>카테고리</h3></li>\r\n");
      out.write("              <li class=\"infomation-item\"><h3>취업상태</h3></li>\r\n");
      out.write("              <li class=\"infomation-item\"><h3>대상</h3></li>\r\n");
      out.write("              <li class=\"infomation-item\"><h3>지역</h3></li>\r\n");
      out.write("          </th>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- 대외활동 글쓰기 카테고리,대상,지역별 선택 -->\r\n");
      out.write(" <div class=\"select_box\">\r\n");
      out.write("          <h3>\r\n");
      out.write("              <select class=\"categoty_select\" id=\"sp_category\" name=\"sp_category\">\r\n");
      out.write("                  <option value=\"선택\" ");
      out.print( categoryarr[0] );
      out.write("  selected disabled hidden >선택해주세요.</option>\r\n");
      out.write("                  <option value=\"재직지원\" ");
      out.print( categoryarr[1] );
      out.write(" >재직지원</option>\r\n");
      out.write("                  <option value=\"취업지원\" ");
      out.print( categoryarr[2] );
      out.write(" >취업지원</option>\r\n");
      out.write("                  <option value=\"기업지원\" ");
      out.print( categoryarr[3] );
      out.write(" >기업지원</option>\r\n");
      out.write("                  <option value=\"창업지원\" ");
      out.print( categoryarr[4] );
      out.write(" >창업지원</option>\r\n");
      out.write("                  <option value=\"생활/금융\" ");
      out.print( categoryarr[5] );
      out.write(" >생활/금융</option>\r\n");
      out.write("                  <option value=\"교통/주거\" ");
      out.print( categoryarr[6] );
      out.write(" >교통/주거</option>\r\n");
      out.write("              </select>\r\n");
      out.write("          </h3>\r\n");
      out.write("          <h3>\r\n");
      out.write("          \t<div>\r\n");
      out.write("          \t\t <button type=\"button\" class=\"select_btn\" id=\"sp_em\">재직중</button>\r\n");
      out.write("                  <button type=\"button\" class=\"select_btn\" id=\"sp_nem\">구직중</button>\r\n");
      out.write("           \t</div>\r\n");
      out.write("           \t<div id=\"ck_sp_emState\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_em\" id=\"ck_sp_em\" value=\"재직중\" ");
      out.print( emStatearr[0] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_em\" id=\"ck_sp_nem\" value=\"구직중\" ");
      out.print( emStatearr[1] );
      out.write(">\r\n");
      out.write("            </div>\r\n");
      out.write("          </h3>\r\n");
      out.write("          <script>\r\n");
      out.write("          \t$(function(){\r\n");
      out.write("          \t\t$(\"#ck_sp_emState\").hide();\r\n");
      out.write("                 $(\"#sp_em\").click(function(){\r\n");
      out.write("                    $(\"#ck_sp_em\").click();\r\n");
      out.write("                    if($(\"#ck_sp_em\").is(\":checked\") == true){\r\n");
      out.write("                   \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                    }else{\r\n");
      out.write("                   \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                    }\r\n");
      out.write("                 });\r\n");
      out.write("                 $(\"#sp_nem\").click(function(){\r\n");
      out.write("                    $(\"#ck_sp_nem\").click();\r\n");
      out.write("                    if($(\"#ck_sp_nem\").is(\":checked\") == true){\r\n");
      out.write("                   \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                    }else{\r\n");
      out.write("                   \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                    }\r\n");
      out.write("                 });\r\n");
      out.write("          \t});\r\n");
      out.write("          </script>\r\n");
      out.write("          <h3>\r\n");
      out.write("              <div>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"sp_age_18\">청년<br>(18~34세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"sp_age_35\">중년<br>(35~49세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"sp_age_50\">장년<br>(50~64세) </button>\r\n");
      out.write("                  <button type=\"button\"class=\"select_btn\" id=\"sp_age_65\">어르신<br>(65세 이상) </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"ck_sp_age\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_age\" id=\"ck_sp_age_18\" value=\"청년\" ");
      out.print( tcarr[0] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_age\" id=\"ck_sp_age_35\" value=\"중년\" ");
      out.print( tcarr[1] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_age\" id=\"ck_sp_age_50\" value=\"장년\" ");
      out.print( tcarr[2] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_sp_age\" id=\"ck_sp_age_65\" value=\"어르신\" ");
      out.print( tcarr[3] );
      out.write(">\r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("            $(document).ready(function(){\r\n");
      out.write("            \tif($(\"#ck_sp_em\").is(\":checked\") == true){\r\n");
      out.write("              \t\t $(\"#sp_em\").css({'background':'darkgray'});\r\n");
      out.write("              \t\t}\r\n");
      out.write("              \t\tif($(\"#ck_sp_nem\").is(\":checked\") == true){\r\n");
      out.write("              \t\t  \t $(\"#sp_nem\").css({'background':'darkgray'});\r\n");
      out.write("              \t    }\r\n");
      out.write("            \tif($(\"#ck_sp_age_18\").is(\":checked\") == true){\r\n");
      out.write("           \t\t $(\"#sp_age_18\").css({'background':'darkgray'});\r\n");
      out.write("           \t\t}\r\n");
      out.write("           \t\tif($(\"#ck_sp_age_35\").is(\":checked\") == true){\r\n");
      out.write("           \t\t  \t $(\"#sp_age_35\").css({'background':'darkgray'});\r\n");
      out.write("           \t    }\r\n");
      out.write("           \t\tif($(\"#ck_sp_age_50\").is(\":checked\") == true){\r\n");
      out.write("           \t\t  \t $(\"#sp_age_50\").css({'background':'darkgray'});\r\n");
      out.write("           \t    }\r\n");
      out.write("           \t\tif($(\"#ck_sp_age_65\").is(\":checked\") == true){\r\n");
      out.write("           \t\t  \t $(\"#sp_age_65\").css({'background':'darkgray'});\r\n");
      out.write("           \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GP\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GP\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GY\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GY\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GC\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GC\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GM\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GM\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GJ\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GJ\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GL\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GL\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GP2\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GP2\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_GP3\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#GP3\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_NYJ\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#NYJ\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_DDC\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#DDC\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_BC\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#BC\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_SN\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#SN\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_SW\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#SW\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_SH\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#SH\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_AS\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#AS\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_AY\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#AY\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_PJ\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#PJ\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_PT\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#PT\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_PC\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#PC\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_HN\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#HN\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("           \t\tif($(\"#ck_HS\").is(\":checked\") == true){\r\n");
      out.write("          \t\t  \t $(\"#HS\").css({'background':'darkgray'});\r\n");
      out.write("          \t    }\r\n");
      out.write("            \t});\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $(\"#ck_sp_age\").hide();\r\n");
      out.write("                $(\"#sp_age_18\").click(function(){\r\n");
      out.write("                   $(\"#ck_sp_age_18\").click();\r\n");
      out.write("                   if($(\"#ck_sp_age_18\").is(\":checked\") == true){\r\n");
      out.write("                  \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                   }else{\r\n");
      out.write("                  \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#sp_age_35\").click(function(){\r\n");
      out.write("                   $(\"#ck_sp_age_35\").click();\r\n");
      out.write("                   if($(\"#ck_sp_age_35\").is(\":checked\") == true){\r\n");
      out.write("                  \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                   }else{\r\n");
      out.write("                  \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#sp_age_50\").click(function(){\r\n");
      out.write("                   $(\"#ck_sp_age_50\").click();\r\n");
      out.write("                   if($(\"#ck_sp_age_50\").is(\":checked\") == true){\r\n");
      out.write("                  \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                   }else{\r\n");
      out.write("                  \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#sp_age_65\").click(function(){\r\n");
      out.write("                   $(\"#ck_sp_age_65\").click();\r\n");
      out.write("                   if($(\"#ck_sp_age_65\").is(\":checked\") == true){\r\n");
      out.write("                  \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                   }else{\r\n");
      out.write("                  \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("             });\r\n");
      out.write("         </script>\r\n");
      out.write("          </h3>\r\n");
      out.write("          <h3 id = \"sp_areatable_div\">\r\n");
      out.write("              <div id= \"sp_areatable\">\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GP\">가평군</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GY\">고양시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GC\">과천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GM\">광명시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GJ\">광주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GL\">구리시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GP2\">군포시</button>\r\n");
      out.write("\t              <br>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"GP3\">김포시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"NYJ\">남양주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"DDC\">동두천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"BC\">부천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"SN\">성남시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"SW\">수원시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"SH\">시흥시</button>\r\n");
      out.write("\t              <br>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"AS\">안산시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"AY\">안양시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"PJ\">파주시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"PT\">평택시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"PC\">포천시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"HN\">하남시</button>\r\n");
      out.write("\t              <button type=\"button\" class = \"select_btn\" id=\"HS\">화성시</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"ck_sp_areatable\">\r\n");
      out.write("             \t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP\" value=\"가평군\" ");
      out.print( lcarr[0] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GY\" value=\"고양시\" ");
      out.print( lcarr[1] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GC\" value=\"과천시\" ");
      out.print( lcarr[2] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GM\" value=\"광명시\" ");
      out.print( lcarr[3] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GJ\" value=\"광주시\" ");
      out.print( lcarr[4] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GL\" value=\"구리시\" ");
      out.print( lcarr[5] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP2\" value=\"군포시\" ");
      out.print( lcarr[6] );
      out.write(">\r\n");
      out.write("              \t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_GP3\" value=\"김포시\" ");
      out.print( lcarr[7] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_NYJ\" value=\"남양주시\" ");
      out.print( lcarr[8] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_DDC\" value=\"동두천시\" ");
      out.print( lcarr[9] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_BC\" value=\"부천시\" ");
      out.print( lcarr[10] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SN\" value=\"성남시\" ");
      out.print( lcarr[11] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SW\" value=\"수원시\" ");
      out.print( lcarr[12] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_SH\" value=\"시흥시\" ");
      out.print( lcarr[13] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_AS\" value=\"안산시\" ");
      out.print( lcarr[14] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_AY\" value=\"안양시\" ");
      out.print( lcarr[15] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PJ\" value=\"파주시\" ");
      out.print( lcarr[16] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PT\" value=\"평택시\" ");
      out.print( lcarr[17] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_PC\" value=\"포천시\" ");
      out.print( lcarr[18] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_HN\" value=\"하남시\" ");
      out.print( lcarr[19] );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ck_lc\" id=\"ck_HS\" value=\"화성시\" ");
      out.print( lcarr[20] );
      out.write(">\r\n");
      out.write("            </div>\r\n");
      out.write("             <script>\r\n");
      out.write("               $(function(){\r\n");
      out.write("                  $(\"#ck_sp_areatable\").hide();\r\n");
      out.write("                  $(\"#GP\").click(function(){\r\n");
      out.write("                     $(\"#ck_GP\").click();\r\n");
      out.write("                     if($(\"#ck_GP\").is(\":checked\") == true){\r\n");
      out.write("                    \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                     }else{\r\n");
      out.write("                    \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#GY\").click(function(){\r\n");
      out.write("                      $(\"#ck_GY\").click();\r\n");
      out.write("                      if($(\"#ck_GY\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GC\").click(function(){\r\n");
      out.write("                      $(\"#ck_GC\").click();\r\n");
      out.write("                      if($(\"#ck_GC\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GM\").click(function(){\r\n");
      out.write("                      $(\"#ck_GM\").click();\r\n");
      out.write("                      if($(\"#ck_GM\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GJ\").click(function(){\r\n");
      out.write("                      $(\"#ck_GJ\").click();\r\n");
      out.write("                      if($(\"#ck_GJ\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GL\").click(function(){\r\n");
      out.write("                      $(\"#ck_GL\").click();\r\n");
      out.write("                      if($(\"#ck_GL\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GP2\").click(function(){\r\n");
      out.write("                      $(\"#ck_GP2\").click();\r\n");
      out.write("                      if($(\"#ck_GP2\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                  $(\"#GP3\").click(function(){\r\n");
      out.write("                      $(\"#ck_GP3\").click();\r\n");
      out.write("                      if($(\"#ck_GP3\").is(\":checked\") == true){\r\n");
      out.write("                     \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                      }else{\r\n");
      out.write("                     \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                      }\r\n");
      out.write("                   });\r\n");
      out.write("                   $(\"#NYJ\").click(function(){\r\n");
      out.write("                       $(\"#ck_NYJ\").click();\r\n");
      out.write("                       if($(\"#ck_NYJ\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#DDC\").click(function(){\r\n");
      out.write("                       $(\"#ck_DDC\").click();\r\n");
      out.write("                       if($(\"#ck_DDC\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#BC\").click(function(){\r\n");
      out.write("                       $(\"#ck_BC\").click();\r\n");
      out.write("                       if($(\"#ck_BC\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SN\").click(function(){\r\n");
      out.write("                       $(\"#ck_SN\").click();\r\n");
      out.write("                       if($(\"#ck_SN\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SW\").click(function(){\r\n");
      out.write("                       $(\"#ck_SW\").click();\r\n");
      out.write("                       if($(\"#ck_SW\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#SH\").click(function(){\r\n");
      out.write("                       $(\"#ck_SH\").click();\r\n");
      out.write("                       if($(\"#ck_SH\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                   $(\"#AS\").click(function(){\r\n");
      out.write("                       $(\"#ck_AS\").click();\r\n");
      out.write("                       if($(\"#ck_AS\").is(\":checked\") == true){\r\n");
      out.write("                      \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                       }else{\r\n");
      out.write("                      \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#AY\").click(function(){\r\n");
      out.write("                        $(\"#ck_AY\").click();\r\n");
      out.write("                        if($(\"#ck_AY\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PJ\").click(function(){\r\n");
      out.write("                        $(\"#ck_PJ\").click();\r\n");
      out.write("                        if($(\"#ck_PJ\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PT\").click(function(){\r\n");
      out.write("                        $(\"#ck_PT\").click();\r\n");
      out.write("                        if($(\"#ck_PT\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#PC\").click(function(){\r\n");
      out.write("                        $(\"#ck_PC\").click();\r\n");
      out.write("                        if($(\"#ck_PC\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#HN\").click(function(){\r\n");
      out.write("                        $(\"#ck_HN\").click();\r\n");
      out.write("                        if($(\"#ck_HN\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                    $(\"#HS\").click(function(){\r\n");
      out.write("                        $(\"#ck_HS\").click();\r\n");
      out.write("                        if($(\"#ck_HS\").is(\":checked\") == true){\r\n");
      out.write("                       \t $(this).css({'background':'darkgray'});\r\n");
      out.write("                        }else{\r\n");
      out.write("                       \t $(this).css('background', 'RGB(221,228,236)');\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("               });\r\n");
      out.write("           </script>\r\n");
      out.write("          </h3>\r\n");
      out.write("      </div>  \r\n");
      out.write("      <!-- </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 대외활동 글쓰기 카테고리,대상,지역별 선택 -->\r\n");
      out.write("    <div class=\"writer_box\">\r\n");
      out.write("    <input type=\"hidden\" size=\"50\" name=\"no\" value=\"");
      out.print( b.getBoardNo() );
      out.write("\">\r\n");
      out.write("     <table class=\"writer_table\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th width=\"15%\">제목</th>\r\n");
      out.write("            <td width=\"50%\" colspan=\"3\"><input type =\"text\" name = \"sp_title\" placeholder=\"제목을 입력하세요.\" class=textline1 value=\"");
      out.print(b.getBoardTitle() );
      out.write("\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>현재 메인 이미지</th>\r\n");
      out.write("            <td colspan=\"3\" name=\"sp_orgin_title_image\" value=\"");
      out.print(titleImg.getOriginName() );
      out.write('"');
      out.write('>');
      out.print( titleImg.getOriginName() );
      out.write("</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>메인 이미지 수정</th>\r\n");
      out.write("            <td colspan=\"3\"><input type =\"file\" multiple=\"multiple\" id=\"sp_title_image\" name = \"sp_title_image\" class=textline2></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>모집 일정</th>\r\n");
      out.write("            <td colspan=\"3\"><input type =\"date\" id=\"sp_res_date\"name = \"sp_res_date\"  class=dateline1  value=\"");
      out.print(b.getReStartDate() );
      out.write("\">\r\n");
      out.write("              ~ <input type =\"date\" id=\"ea_ree_date\"name = \"sp_ree_date\"  class=dateline1 value=\"");
      out.print(b.getReEndDate() );
      out.write("\"> 까지</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>내용</th>\r\n");
      out.write("            <td><textarea class=\"form-control\" name=\"sp_text_contents\" id=\"sp_text_Contents\" placeholder=\"내용을 입력해 주세요\" >");
      out.print(b.getBoardContent() );
      out.write("</textarea></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("           ");
if(fList.size()>1){ 
      out.write("\r\n");
      out.write("\t          \t<tr>\r\n");
      out.write("\t            <th>현재 참고자료</th>\r\n");
      out.write("\t            <td>");
      out.print( fList.get(1).getOriginName() );
      out.write("</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t            <th>참고자료 수정</th>\r\n");
      out.write("\t            <td colspan=\"3\"><input type =\"file\"  multiple=\"multiple\" id=\"sp_main_image\" name = \"sp_main_image\" class=textline2></td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t            <th>참고자료</th>\r\n");
      out.write("\t            <td colspan=\"3\"><input type =\"file\"  multiple=\"multiple\" id=\"sp_main_image\" name = \"titleImage\" class=textline2></td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class = \"sp_button\">\r\n");
      out.write("      <input type=\"submit\" id=\"insertBtn\" value=\"작성완료\">\r\n");
      out.write("      <input type=\"button\" id=\"cancelBtn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/spMain.cm'\" value=\"취소하기\">\r\n");
      out.write("    </div>\r\n");
      out.write("\t</script>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>  \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("  color: black;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  height: 1px;\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  border: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding-top: 10px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 3%;\r\n");
      out.write("  padding-top: 3%;\r\n");
      out.write("  background-color: rgb(15, 76, 130);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_box {\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  color: rgb(255, 213, 0);\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<footer>\r\n");
      out.write("   <div class=\"footer_box\">\r\n");
      out.write("      Copyrightⓒ2020 Flower than java Project All Rights Reserved.\r\n");
      out.write("   </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
